// Copyright 2020 Fortinet, Inc. All rights reserved.
// Author: Frank Shen (@frankshen01), Hongbin Lu (@fgtdev-hblu)
// Documentation:
// Frank Shen (@frankshen01), Hongbin Lu (@fgtdev-hblu),
// Yuffie Zhu (@yuffiezhu), Yue Wang (@yuew-ftnt)

// Description: Provider for FortiOS

package fortios

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/terraform"
)

// Provider creates and returns the FortiOS terraform.ResourceProvider
func Provider() terraform.ResourceProvider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"hostname": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "The hostname/IP address of the FortiOS to be connected",
			},

			"token": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "",
			},

			"insecure": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "",
			},

			"cabundlefile": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "CA Bundle file",
			},

			"vdom": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "",
			},

			"fmg_hostname": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "Hostname/IP address of the FortiManager to connect to",
			},

			"fmg_username": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "",
			},

			"fmg_passwd": &schema.Schema{
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "",
			},

			"fmg_insecure": {
				Type:        schema.TypeBool,
				Optional:    true,
				Description: "",
			},

			"fmg_cabundlefile": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				Description: "CA Bundle file",
			},
		},

		ResourcesMap: map[string]*schema.Resource{
			"fortios_networking_route_static":                 resourceNetworkingRouteStatic(),
			"fortios_networking_interface_port":               resourceNetworkingInterfacePort(),
			"fortios_system_admin_profiles":                   resourceSystemAdminProfiles(),
			"fortios_system_admin_administrator":              resourceSystemAdminAdministrator(),
			"fortios_firewall_object_address":                 resourceFirewallObjectAddress(),
			"fortios_firewall_object_addressgroup":            resourceFirewallObjectAddressGroup(),
			"fortios_firewall_object_service":                 resourceFirewallObjectService(),
			"fortios_firewall_object_servicegroup":            resourceFirewallObjectServiceGroup(),
			"fortios_firewall_object_servicecategory":         resourceFirewallObjectServiceCategory(),
			"fortios_firewall_object_vip":                     resourceFirewallObjectVip(),
			"fortios_firewall_object_vipgroup":                resourceFirewallObjectVipGroup(),
			"fortios_firewall_object_ippool":                  resourceFirewallObjectIPPool(),
			"fortios_firewall_security_policy":                resourceFirewallSecurityPolicy(),
			"fortios_firewall_security_policyseq":             resourceFirewallSecurityPolicySeq(),
			"fortios_system_setting_global":                   resourceSystemSettingGlobal(),
			"fortios_system_setting_dns":                      resourceSystemSettingDNS(),
			"fortios_system_setting_ntp":                      resourceSystemSettingNTP(),
			"fortios_log_syslog_setting":                      resourceLogSyslogSetting(),
			"fortios_log_fortianalyzer_setting":               resourceLogFortiAnalyzerSetting(),
			"fortios_system_apiuser_setting":                  resourceSystemAPIUserSetting(),
			"fortios_system_vdom_setting":                     resourceSystemVdomSetting(),
			"fortios_system_license_forticare":                resourceSystemLicenseFortiCare(),
			"fortios_system_license_vdom":                     resourceSystemLicenseVDOM(),
			"fortios_system_license_vm":                       resourceSystemLicenseVM(),
			"fortios_vpn_ipsec_phase1interface":               resourceVPNIPsecPhase1Interface(),
			"fortios_vpn_ipsec_phase2interface":               resourceVPNIPsecPhase2Interface(),
			"fortios_json_generic_api":                        resourceJSONGenericAPI(),
			"fortios_fmg_system_admin_profiles":               resourceFortimanagerSystemAdminProfiles(),
			"fortios_fmg_system_admin_user":                   resourceFortimanagerSystemAdminUser(),
			"fortios_fmg_devicemanager_device":                resourceFortimanagerDVMDevice(),
			"fortios_fmg_devicemanager_script":                resourceFortimanagerDVMScript(),
			"fortios_fmg_devicemanager_script_execute":        resourceFortimanagerDVMScriptExecute(),
			"fortios_fmg_devicemanager_install_device":        resourceFortimanagerDVMInstallDev(),
			"fortios_fmg_devicemanager_install_policypackage": resourceFortimanagerDVMInstallPolicyPackage(),
			"fortios_fmg_firewall_security_policy":            resourceFortimanagerFirewallSecurityPolicy(),
			"fortios_fmg_firewall_security_policypackage":     resourceFortimanagerFirewallSecurityPolicyPackage(),
			"fortios_fmg_object_adom_revision":                resourceFortimanagerObjectAdomRevision(),
			"fortios_fmg_firewall_object_address":             resourceFortimanagerFirewallObjectAddress(),
			"fortios_fmg_firewall_object_service":             resourceFortimanagerFirewallObjectService(),
			"fortios_fmg_firewall_object_ippool":              resourceFortimanagerFirewallObjectIppool(),
			"fortios_fmg_firewall_object_vip":                 resourceFortimanagerFirewallObjectVip(),
			"fortios_fmg_system_syslogserver":                 resourceFortimanagerSystemSyslogServer(),
			"fortios_fmg_system_network_interface":            resourceFortimanagerSystemNetworkInterface(),
			"fortios_fmg_system_network_route":                resourceFortimanagerSystemNetworkRoute(),
			"fortios_fmg_system_adom":                         resourceFortimanagerSystemAdom(),
			"fortios_fmg_system_global":                       resourceFortimanagerSystemGlobal(),
			"fortios_fmg_system_admin":                        resourceFortimanagerSystemAdmin(),
			"fortios_fmg_system_dns":                          resourceFortimanagerSystemDNS(),
			"fortios_fmg_system_ntp":                          resourceFortimanagerSystemNTP(),
			"fortios_fmg_system_license_vm":                   resourceFortimanagerSystemLicenseVM(),
			"fortios_fmg_system_license_forticare":            resourceFortimanagerSystemLicenseFortiCare(),
			"fortios_fmg_jsonrpc_request":                     resourceFortimanagerJSONRPCRequest(),

			"fortios_system_global": resourceSystemGlobal(),
			"fortios_system_accprofile": resourceSystemAccprofile(),
			"fortios_system_objecttagging": resourceSystemObjectTagging(),
			"fortios_system_interface": resourceSystemInterface(),
			"fortios_system_passwordpolicy": resourceSystemPasswordPolicy(),
			"fortios_system_passwordpolicyguestadmin": resourceSystemPasswordPolicyGuestAdmin(),
			"fortios_system_smsserver": resourceSystemSmsServer(),
			"fortios_system_admin": resourceSystemAdmin(),
			"fortios_system_apiuser": resourceSystemApiUser(),
			"fortios_system_sittunnel": resourceSystemSitTunnel(),
			"fortios_system_fssopolling": resourceSystemFssoPolling(),
			"fortios_system_ha": resourceSystemHa(),
			"fortios_system_hamonitor": resourceSystemHaMonitor(),
			"fortios_system_arptable": resourceSystemArpTable(),
			"fortios_system_ipv6neighborcache": resourceSystemIpv6NeighborCache(),
			"fortios_system_dns": resourceSystemDns(),
			"fortios_system_ddns": resourceSystemDdns(),
			"fortios_system_sflow": resourceSystemSflow(),
			"fortios_system_vdomsflow": resourceSystemVdomSflow(),
			"fortios_system_netflow": resourceSystemNetflow(),
			"fortios_system_vdomnetflow": resourceSystemVdomNetflow(),
			"fortios_system_replacemsgimage": resourceSystemReplacemsgImage(),
			"fortios_system_replacemsggroup": resourceSystemReplacemsgGroup(),
			"fortios_systemsnmp_sysinfo": resourceSystemSnmpSysinfo(),
			"fortios_systemsnmp_community": resourceSystemSnmpCommunity(),
			"fortios_systemsnmp_user": resourceSystemSnmpUser(),
			"fortios_systemautoupdate_pushupdate": resourceSystemAutoupdatePushUpdate(),
			"fortios_systemautoupdate_schedule": resourceSystemAutoupdateSchedule(),
			"fortios_systemautoupdate_tunneling": resourceSystemAutoupdateTunneling(),
			"fortios_system_sessionttl": resourceSystemSessionTtl(),
			"fortios_systemdhcp_server": resourceSystemDhcpServer(),
			"fortios_system_alias": resourceSystemAlias(),
			"fortios_system_autoscript": resourceSystemAutoScript(),
			"fortios_system_managementtunnel": resourceSystemManagementTunnel(),
			"fortios_system_fortimanager": resourceSystemFortimanager(),
			"fortios_system_fm": resourceSystemFm(),
			"fortios_system_centralmanagement": resourceSystemCentralManagement(),
			"fortios_system_zone": resourceSystemZone(),
			"fortios_system_sdnconnector": resourceSystemSdnConnector(),
			"fortios_system_ipv6tunnel": resourceSystemIpv6Tunnel(),
			"fortios_system_externalresource": resourceSystemExternalResource(),
			"fortios_system_networkvisibility": resourceSystemNetworkVisibility(),
			"fortios_system_gretunnel": resourceSystemGreTunnel(),
			"fortios_system_ipsecaggregate": resourceSystemIpsecAggregate(),
			"fortios_system_ipiptunnel": resourceSystemIpipTunnel(),
			"fortios_system_mobiletunnel": resourceSystemMobileTunnel(),
			"fortios_system_pppoeinterface": resourceSystemPppoeInterface(),
			"fortios_system_vxlan": resourceSystemVxlan(),
			"fortios_system_dnsdatabase": resourceSystemDnsDatabase(),
			"fortios_system_dnsserver": resourceSystemDnsServer(),
			"fortios_system_resourcelimits": resourceSystemResourceLimits(),
			"fortios_system_virtualwanlink": resourceSystemVirtualWanLink(),
			"fortios_systemlldp_networkpolicy": resourceSystemLldpNetworkPolicy(),
			"fortios_system_clustersync": resourceSystemClusterSync(),
			"fortios_system_fortiguard": resourceSystemFortiguard(),
			"fortios_system_emailserver": resourceSystemEmailServer(),
			"fortios_system_sessionhelper": resourceSystemSessionHelper(),
			"fortios_system_proxyarp": resourceSystemProxyArp(),
			"fortios_system_fipscc": resourceSystemFipsCc(),
			"fortios_system_tosbasedpriority": resourceSystemTosBasedPriority(),
			"fortios_system_dscpbasedpriority": resourceSystemDscpBasedPriority(),
			"fortios_system_proberesponse": resourceSystemProbeResponse(),
			"fortios_system_linkmonitor": resourceSystemLinkMonitor(),
			"fortios_system_autoinstall": resourceSystemAutoInstall(),
			"fortios_system_console": resourceSystemConsole(),
			"fortios_system_ntp": resourceSystemNtp(),
			"fortios_system_wccp": resourceSystemWccp(),
			"fortios_system_nat64": resourceSystemNat64(),
			"fortios_system_ftmpush": resourceSystemFtmPush(),
			"fortios_system_fortisandbox": resourceSystemFortisandbox(),
			"fortios_system_vdomexception": resourceSystemVdomException(),
			"fortios_system_csf": resourceSystemCsf(),
			"fortios_system_automationtrigger": resourceSystemAutomationTrigger(),
			"fortios_system_automationaction": resourceSystemAutomationAction(),
			"fortios_system_automationdestination": resourceSystemAutomationDestination(),
			"fortios_system_ndproxy": resourceSystemNdProxy(),
			"fortios_wirelesscontroller_intercontroller": resourceWirelessControllerInterController(),
			"fortios_wirelesscontroller_global": resourceWirelessControllerGlobal(),
			"fortios_wirelesscontrollerhotspot20_anqpvenuename": resourceWirelessControllerHotspot20AnqpVenueName(),
			"fortios_wirelesscontrollerhotspot20_anqpnetworkauthtype": resourceWirelessControllerHotspot20AnqpNetworkAuthType(),
			"fortios_wirelesscontrollerhotspot20_anqproamingconsortium": resourceWirelessControllerHotspot20AnqpRoamingConsortium(),
			"fortios_wirelesscontrollerhotspot20_anqp3gppcellular": resourceWirelessControllerHotspot20Anqp3GppCellular(),
			"fortios_wirelesscontrollerhotspot20_anqpipaddresstype": resourceWirelessControllerHotspot20AnqpIpAddressType(),
			"fortios_wirelesscontrollerhotspot20_h2qpoperatorname": resourceWirelessControllerHotspot20H2QpOperatorName(),
			"fortios_wirelesscontrollerhotspot20_h2qpwanmetric": resourceWirelessControllerHotspot20H2QpWanMetric(),
			"fortios_wirelesscontrollerhotspot20_h2qpconncapability": resourceWirelessControllerHotspot20H2QpConnCapability(),
			"fortios_wirelesscontrollerhotspot20_icon": resourceWirelessControllerHotspot20Icon(),
			"fortios_switchcontroller_trafficpolicy": resourceSwitchControllerTrafficPolicy(),
			"fortios_switchcontroller_switchinterfacetag": resourceSwitchControllerSwitchInterfaceTag(),
			"fortios_switchcontroller_8021Xsettings": resourceSwitchController8021XSettings(),
			"fortios_switchcontrollersecuritypolicy_8021X": resourceSwitchControllerSecurityPolicy8021X(),
			"fortios_switchcontroller_lldpsettings": resourceSwitchControllerLldpSettings(),
			"fortios_switchcontroller_lldpprofile": resourceSwitchControllerLldpProfile(),
			"fortios_switchcontrollerqos_dot1pmap": resourceSwitchControllerQosDot1PMap(),
			"fortios_switchcontrollerqos_ipdscpmap": resourceSwitchControllerQosIpDscpMap(),
			"fortios_switchcontrollerqos_queuepolicy": resourceSwitchControllerQosQueuePolicy(),
			"fortios_switchcontroller_switchprofile": resourceSwitchControllerSwitchProfile(),
			"fortios_switchcontroller_customcommand": resourceSwitchControllerCustomCommand(),
			"fortios_switchcontroller_virtualportpool": resourceSwitchControllerVirtualPortPool(),
			"fortios_switchcontroller_stpsettings": resourceSwitchControllerStpSettings(),
			"fortios_switchcontroller_switchlog": resourceSwitchControllerSwitchLog(),
			"fortios_switchcontroller_igmpsnooping": resourceSwitchControllerIgmpSnooping(),
			"fortios_switchcontroller_sflow": resourceSwitchControllerSflow(),
			"fortios_switchcontroller_networkmonitorsettings": resourceSwitchControllerNetworkMonitorSettings(),
			"fortios_extendercontroller_extender": resourceExtenderControllerExtender(),
			"fortios_firewall_address": resourceFirewallAddress(),
			"fortios_firewall_multicastaddress": resourceFirewallMulticastAddress(),
			"fortios_firewall_address6template": resourceFirewallAddress6Template(),
			"fortios_firewall_address6": resourceFirewallAddress6(),
			"fortios_firewall_multicastaddress6": resourceFirewallMulticastAddress6(),
			"fortios_firewall_addrgrp": resourceFirewallAddrgrp(),
			"fortios_firewall_addrgrp6": resourceFirewallAddrgrp6(),
			"fortios_firewallwildcardfqdn_custom": resourceFirewallWildcardFqdnCustom(),
			"fortios_firewallwildcardfqdn_group": resourceFirewallWildcardFqdnGroup(),
			"fortios_firewallservice_category": resourceFirewallServiceCategory(),
			"fortios_firewallservice_custom": resourceFirewallServiceCustom(),
			"fortios_firewallservice_group": resourceFirewallServiceGroup(),
			"fortios_firewall_internetserviceextension": resourceFirewallInternetServiceExtension(),
			"fortios_firewallshaper_trafficshaper": resourceFirewallShaperTrafficShaper(),
			"fortios_firewallshaper_peripshaper": resourceFirewallShaperPerIpShaper(),
			"fortios_firewall_proxyaddress": resourceFirewallProxyAddress(),
			"fortios_firewallschedule_onetime": resourceFirewallScheduleOnetime(),
			"fortios_firewallschedule_recurring": resourceFirewallScheduleRecurring(),
			"fortios_firewallschedule_group": resourceFirewallScheduleGroup(),
			"fortios_firewall_ippool": resourceFirewallIppool(),
			"fortios_firewall_ippool6": resourceFirewallIppool6(),
			"fortios_firewall_ldbmonitor": resourceFirewallLdbMonitor(),
			"fortios_firewall_vip": resourceFirewallVip(),
			"fortios_firewall_vip46": resourceFirewallVip46(),
			"fortios_firewall_vip6": resourceFirewallVip6(),
			"fortios_firewall_vip64": resourceFirewallVip64(),
			"fortios_firewall_vipgrp": resourceFirewallVipgrp(),
			"fortios_firewall_vipgrp46": resourceFirewallVipgrp46(),
			"fortios_firewall_vipgrp6": resourceFirewallVipgrp6(),
			"fortios_firewall_vipgrp64": resourceFirewallVipgrp64(),
			"fortios_firewallipmacbinding_setting": resourceFirewallIpmacbindingSetting(),
			"fortios_firewallipmacbinding_table": resourceFirewallIpmacbindingTable(),
			"fortios_firewall_profilegroup": resourceFirewallProfileGroup(),
			"fortios_firewall_sslserver": resourceFirewallSslServer(),
			"fortios_firewall_identitybasedroute": resourceFirewallIdentityBasedRoute(),
			"fortios_firewall_authportal": resourceFirewallAuthPortal(),
			"fortios_firewall_policy": resourceFirewallPolicy(),
			"fortios_firewall_shapingpolicy": resourceFirewallShapingPolicy(),
			"fortios_firewall_shapingprofile": resourceFirewallShapingProfile(),
			"fortios_firewall_localinpolicy": resourceFirewallLocalInPolicy(),
			"fortios_firewall_policy6": resourceFirewallPolicy6(),
			"fortios_firewall_localinpolicy6": resourceFirewallLocalInPolicy6(),
			"fortios_firewall_ttlpolicy": resourceFirewallTtlPolicy(),
			"fortios_firewall_policy64": resourceFirewallPolicy64(),
			"fortios_firewall_proxypolicy": resourceFirewallProxyPolicy(),
			"fortios_firewall_dnstranslation": resourceFirewallDnstranslation(),
			"fortios_firewall_multicastpolicy": resourceFirewallMulticastPolicy(),
			"fortios_firewall_multicastpolicy6": resourceFirewallMulticastPolicy6(),
			"fortios_firewall_interfacepolicy": resourceFirewallInterfacePolicy(),
			"fortios_firewall_interfacepolicy6": resourceFirewallInterfacePolicy6(),
			"fortios_firewall_sniffer": resourceFirewallSniffer(),
			"fortios_firewall_centralsnatmap": resourceFirewallCentralSnatMap(),
			"fortios_firewallssl_setting": resourceFirewallSslSetting(),
			"fortios_firewallssh_setting": resourceFirewallSshSetting(),
			"fortios_firewallssh_hostkey": resourceFirewallSshHostKey(),
			"fortios_firewall_iptranslation": resourceFirewallIpTranslation(),
			"fortios_vpncertificate_ocspserver": resourceVpnCertificateOcspServer(),
			"fortios_vpncertificate_setting": resourceVpnCertificateSetting(),
			"fortios_vpnsslweb_realm": resourceVpnSslWebRealm(),
			"fortios_vpnsslweb_hostchecksoftware": resourceVpnSslWebHostCheckSoftware(),
			"fortios_vpnsslweb_portal": resourceVpnSslWebPortal(),
			"fortios_vpnsslweb_usergroupbookmark": resourceVpnSslWebUserGroupBookmark(),
			"fortios_vpnsslweb_userbookmark": resourceVpnSslWebUserBookmark(),
			"fortios_vpnssl_settings": resourceVpnSslSettings(),
			"fortios_vpnipsec_phase1": resourceVpnIpsecPhase1(),
			"fortios_vpnipsec_phase2": resourceVpnIpsecPhase2(),
			"fortios_vpnipsec_manualkey": resourceVpnIpsecManualkey(),
			"fortios_vpnipsec_concentrator": resourceVpnIpsecConcentrator(),
			"fortios_vpnipsec_phase1interface": resourceVpnIpsecPhase1Interface(),
			"fortios_vpnipsec_phase2interface": resourceVpnIpsecPhase2Interface(),
			"fortios_vpnipsec_manualkeyinterface": resourceVpnIpsecManualkeyInterface(),
			"fortios_vpnipsec_forticlient": resourceVpnIpsecForticlient(),
			"fortios_webfilter_ftgdlocalcat": resourceWebfilterFtgdLocalCat(),
			"fortios_webfilter_content": resourceWebfilterContent(),
			"fortios_webfilter_contentheader": resourceWebfilterContentHeader(),
			"fortios_webfilter_urlfilter": resourceWebfilterUrlfilter(),
			"fortios_webfilter_ipsurlfiltersetting": resourceWebfilterIpsUrlfilterSetting(),
			"fortios_webfilter_ipsurlfiltersetting6": resourceWebfilterIpsUrlfilterSetting6(),
			"fortios_webfilter_ipsurlfiltercachesetting": resourceWebfilterIpsUrlfilterCacheSetting(),
			"fortios_webfilter_profile": resourceWebfilterProfile(),
			"fortios_webfilter_fortiguard": resourceWebfilterFortiguard(),
			"fortios_webfilter_override": resourceWebfilterOverride(),
			"fortios_webfilter_ftgdlocalrating": resourceWebfilterFtgdLocalRating(),
			"fortios_webfilter_searchengine": resourceWebfilterSearchEngine(),
			"fortios_ips_global": resourceIpsGlobal(),
			"fortios_ips_settings": resourceIpsSettings(),
			"fortios_webproxy_profile": resourceWebProxyProfile(),
			"fortios_webproxy_global": resourceWebProxyGlobal(),
			"fortios_webproxy_forwardserver": resourceWebProxyForwardServer(),
			"fortios_webproxy_forwardservergroup": resourceWebProxyForwardServerGroup(),
			"fortios_webproxy_debugurl": resourceWebProxyDebugUrl(),
			"fortios_webproxy_wisp": resourceWebProxyWisp(),
			"fortios_webproxy_urlmatch": resourceWebProxyUrlMatch(),
			"fortios_wanopt_webcache": resourceWanoptWebcache(),
			"fortios_wanopt_settings": resourceWanoptSettings(),
			"fortios_wanopt_peer": resourceWanoptPeer(),
			"fortios_wanopt_authgroup": resourceWanoptAuthGroup(),
			"fortios_wanopt_contentdeliverynetworkrule": resourceWanoptContentDeliveryNetworkRule(),
			"fortios_wanopt_cacheservice": resourceWanoptCacheService(),
			"fortios_wanopt_remotestorage": resourceWanoptRemoteStorage(),
			"fortios_ftpproxy_explicit": resourceFtpProxyExplicit(),
			"fortios_application_list": resourceApplicationList(),
			"fortios_application_group": resourceApplicationGroup(),
			"fortios_dlp_filepattern": resourceDlpFilepattern(),
			"fortios_dlp_fpsensitivity": resourceDlpFpSensitivity(),
			"fortios_dlp_fpdocsource": resourceDlpFpDocSource(),
			"fortios_dlp_sensor": resourceDlpSensor(),
			"fortios_dlp_settings": resourceDlpSettings(),
			"fortios_spamfilter_bword": resourceSpamfilterBword(),
			"fortios_spamfilter_bwl": resourceSpamfilterBwl(),
			"fortios_spamfilter_mheader": resourceSpamfilterMheader(),
			"fortios_spamfilter_dnsbl": resourceSpamfilterDnsbl(),
			"fortios_spamfilter_profile": resourceSpamfilterProfile(),
			"fortios_spamfilter_fortishield": resourceSpamfilterFortishield(),
			"fortios_spamfilter_options": resourceSpamfilterOptions(),
			"fortios_log_threatweight": resourceLogThreatWeight(),
			"fortios_log_customfield": resourceLogCustomField(),
			"fortios_logsyslogd_setting": resourceLogSyslogdSetting(),
			"fortios_logsyslogd_filter": resourceLogSyslogdFilter(),
			"fortios_logsyslogd_overridefilter": resourceLogSyslogdOverrideFilter(),
			"fortios_logsyslogd2_setting": resourceLogSyslogd2Setting(),
			"fortios_logsyslogd2_filter": resourceLogSyslogd2Filter(),
			"fortios_logsyslogd2_overridefilter": resourceLogSyslogd2OverrideFilter(),
			"fortios_logsyslogd3_setting": resourceLogSyslogd3Setting(),
			"fortios_logsyslogd3_filter": resourceLogSyslogd3Filter(),
			"fortios_logsyslogd3_overridefilter": resourceLogSyslogd3OverrideFilter(),
			"fortios_logsyslogd4_setting": resourceLogSyslogd4Setting(),
			"fortios_logsyslogd4_filter": resourceLogSyslogd4Filter(),
			"fortios_logsyslogd4_overridefilter": resourceLogSyslogd4OverrideFilter(),
			"fortios_logwebtrends_setting": resourceLogWebtrendsSetting(),
			"fortios_logwebtrends_filter": resourceLogWebtrendsFilter(),
			"fortios_logmemory_globalsetting": resourceLogMemoryGlobalSetting(),
			"fortios_logmemory_setting": resourceLogMemorySetting(),
			"fortios_logmemory_filter": resourceLogMemoryFilter(),
			"fortios_logdisk_setting": resourceLogDiskSetting(),
			"fortios_logdisk_filter": resourceLogDiskFilter(),
			"fortios_log_eventfilter": resourceLogEventfilter(),
			"fortios_logfortiguard_setting": resourceLogFortiguardSetting(),
			"fortios_logfortiguard_overridesetting": resourceLogFortiguardOverrideSetting(),
			"fortios_logfortiguard_filter": resourceLogFortiguardFilter(),
			"fortios_logfortiguard_overridefilter": resourceLogFortiguardOverrideFilter(),
			"fortios_lognulldevice_setting": resourceLogNullDeviceSetting(),
			"fortios_lognulldevice_filter": resourceLogNullDeviceFilter(),
			"fortios_log_setting": resourceLogSetting(),
			"fortios_log_guidisplay": resourceLogGuiDisplay(),
			"fortios_logfortianalyzer_setting": resourceLogFortianalyzerSetting(),
			"fortios_logfortianalyzer_overridesetting": resourceLogFortianalyzerOverrideSetting(),
			"fortios_logfortianalyzer_filter": resourceLogFortianalyzerFilter(),
			"fortios_logfortianalyzer_overridefilter": resourceLogFortianalyzerOverrideFilter(),
			"fortios_logfortianalyzer2_setting": resourceLogFortianalyzer2Setting(),
			"fortios_logfortianalyzer2_overridesetting": resourceLogFortianalyzer2OverrideSetting(),
			"fortios_logfortianalyzer2_filter": resourceLogFortianalyzer2Filter(),
			"fortios_logfortianalyzer2_overridefilter": resourceLogFortianalyzer2OverrideFilter(),
			"fortios_logfortianalyzer3_setting": resourceLogFortianalyzer3Setting(),
			"fortios_logfortianalyzer3_overridesetting": resourceLogFortianalyzer3OverrideSetting(),
			"fortios_logfortianalyzer3_filter": resourceLogFortianalyzer3Filter(),
			"fortios_logfortianalyzer3_overridefilter": resourceLogFortianalyzer3OverrideFilter(),
			"fortios_icap_server": resourceIcapServer(),
			"fortios_icap_profile": resourceIcapProfile(),
			"fortios_sshfilter_profile": resourceSshFilterProfile(),
			"fortios_user_radius": resourceUserRadius(),
			"fortios_user_tacacs": resourceUserTacacs(),
			"fortios_user_ldap": resourceUserLdap(),
			"fortios_user_krbkeytab": resourceUserKrbKeytab(),
			"fortios_user_domaincontroller": resourceUserDomainController(),
			"fortios_user_pop3": resourceUserPop3(),
			"fortios_user_fsso": resourceUserFsso(),
			"fortios_user_adgrp": resourceUserAdgrp(),
			"fortios_user_passwordpolicy": resourceUserPasswordPolicy(),
			"fortios_user_local": resourceUserLocal(),
			"fortios_user_setting": resourceUserSetting(),
			"fortios_user_peer": resourceUserPeer(),
			"fortios_user_peergrp": resourceUserPeergrp(),
			"fortios_user_quarantine": resourceUserQuarantine(),
			"fortios_user_group": resourceUserGroup(),
			"fortios_user_device": resourceUserDevice(),
			"fortios_user_deviceaccesslist": resourceUserDeviceAccessList(),
			"fortios_voip_profile": resourceVoipProfile(),
			"fortios_dnsfilter_domainfilter": resourceDnsfilterDomainFilter(),
			"fortios_dnsfilter_profile": resourceDnsfilterProfile(),
			"fortios_antivirus_settings": resourceAntivirusSettings(),
			"fortios_antivirus_heuristic": resourceAntivirusHeuristic(),
			"fortios_antivirus_quarantine": resourceAntivirusQuarantine(),
			"fortios_antivirus_profile": resourceAntivirusProfile(),
			"fortios_report_dataset": resourceReportDataset(),
			"fortios_report_chart": resourceReportChart(),
			"fortios_report_style": resourceReportStyle(),
			"fortios_report_theme": resourceReportTheme(),
			"fortios_report_layout": resourceReportLayout(),
			"fortios_report_setting": resourceReportSetting(),
			"fortios_waf_profile": resourceWafProfile(),
			"fortios_authentication_scheme": resourceAuthenticationScheme(),
			"fortios_authentication_rule": resourceAuthenticationRule(),
			"fortios_authentication_setting": resourceAuthenticationSetting(),
			"fortios_endpointcontrol_settings": resourceEndpointControlSettings(),
			"fortios_endpointcontrol_profile": resourceEndpointControlProfile(),
			"fortios_endpointcontrol_forticlientregistrationsync": resourceEndpointControlForticlientRegistrationSync(),
			"fortios_alertemail_setting": resourceAlertemailSetting(),
			"fortios_router_accesslist": resourceRouterAccessList(),
			"fortios_router_accesslist6": resourceRouterAccessList6(),
			"fortios_router_prefixlist": resourceRouterPrefixList(),
			"fortios_router_prefixlist6": resourceRouterPrefixList6(),
			"fortios_router_keychain": resourceRouterKeyChain(),
			"fortios_router_communitylist": resourceRouterCommunityList(),
			"fortios_router_routemap": resourceRouterRouteMap(),
			"fortios_router_rip": resourceRouterRip(),
			"fortios_router_ripng": resourceRouterRipng(),
			"fortios_router_static": resourceRouterStatic(),
			"fortios_router_policy": resourceRouterPolicy(),
			"fortios_router_policy6": resourceRouterPolicy6(),
			"fortios_router_static6": resourceRouterStatic6(),
			"fortios_router_ospf": resourceRouterOspf(),
			"fortios_router_ospf6": resourceRouterOspf6(),
			"fortios_router_bgp": resourceRouterBgp(),
			"fortios_router_isis": resourceRouterIsis(),
			"fortios_router_multicastflow": resourceRouterMulticastFlow(),
			"fortios_router_multicast": resourceRouterMulticast(),
			"fortios_router_multicast6": resourceRouterMulticast6(),
			"fortios_router_authpath": resourceRouterAuthPath(),
			"fortios_router_setting": resourceRouterSetting(),
 		},

		ConfigureFunc: providerConfigure,
	}
}

func providerConfigure(d *schema.ResourceData) (interface{}, error) {

	// Init client config with the values from TF files
	config := Config{
		Hostname:     d.Get("hostname").(string),
		Token:        d.Get("token").(string),
		CABundle:     d.Get("cabundlefile").(string),
		Vdom:         d.Get("vdom").(string),
		FMG_Hostname: d.Get("fmg_hostname").(string),
		FMG_CABundle: d.Get("fmg_cabundlefile").(string),
		FMG_Username: d.Get("fmg_username").(string),
		FMG_Passwd:   d.Get("fmg_passwd").(string),
	}

	v1, ok1 := d.GetOkExists("insecure")
	if ok1 {
		insecure := v1.(bool)
		config.Insecure = &insecure
	}

	v2, ok2 := d.GetOkExists("fmg_insecure")
	if ok2 {
		insecure := v2.(bool)
		config.FMG_Insecure = &insecure
	}

	// Create Client for later connections
	return config.CreateClient()
}
